name: Deploy "master" branch
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
    - run: composer install --no-progress --no-interaction --no-dev
    - uses: atymic/deployer-php-action@master
      with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.DEPLOY_SSH_KNOWN_HOSTS }}
          deployer-version: 7.0
    - run: dep deploy
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        DEPLOY_HTTP_USER: ${{ secrets.DEPLOY_HTTP_USER }}
