name: Deploy "master" branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - uses: deployphp/action@v1
      with:
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          deployer-version: '7.0.0-beta.38'
          dep: deploy
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        DEPLOY_HTTP_USER: ${{ secrets.DEPLOY_HTTP_USER }}
